// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: examples/go-template-payment/protobuf/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_examples_go_template_payment_protobuf_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_template_payment_protobuf_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_examples_go_template_payment_protobuf_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_template_payment_protobuf_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_examples_go_template_payment_protobuf_user_v1_user_proto protoreflect.FileDescriptor

const file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"8examples/go-template-payment/protobuf/user/v1/user.proto\x12\auser.v1\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2H\n" +
	"\vUserService\x129\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x15.user.v1.UserResponseBZZXgithub.com/opencode-sig/runtime-sdk/examples/go-template-payment/protobuf/user/v1;userv1b\x06proto3"

var (
	file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescOnce sync.Once
	file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescData []byte
)

func file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescGZIP() []byte {
	file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescOnce.Do(func() {
		file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDesc), len(file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDesc)))
	})
	return file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDescData
}

var file_examples_go_template_payment_protobuf_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_go_template_payment_protobuf_user_v1_user_proto_goTypes = []any{
	(*GetUserRequest)(nil), // 0: user.v1.GetUserRequest
	(*UserResponse)(nil),   // 1: user.v1.UserResponse
}
var file_examples_go_template_payment_protobuf_user_v1_user_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	1, // 1: user.v1.UserService.GetUser:output_type -> user.v1.UserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_go_template_payment_protobuf_user_v1_user_proto_init() }
func file_examples_go_template_payment_protobuf_user_v1_user_proto_init() {
	if File_examples_go_template_payment_protobuf_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDesc), len(file_examples_go_template_payment_protobuf_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_go_template_payment_protobuf_user_v1_user_proto_goTypes,
		DependencyIndexes: file_examples_go_template_payment_protobuf_user_v1_user_proto_depIdxs,
		MessageInfos:      file_examples_go_template_payment_protobuf_user_v1_user_proto_msgTypes,
	}.Build()
	File_examples_go_template_payment_protobuf_user_v1_user_proto = out.File
	file_examples_go_template_payment_protobuf_user_v1_user_proto_goTypes = nil
	file_examples_go_template_payment_protobuf_user_v1_user_proto_depIdxs = nil
}
