// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: security/v1/auth.proto

package securityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialType string                 `protobuf:"bytes,1,opt,name=credential_type,json=credentialType,proto3" json:"credential_type,omitempty"`
	Credential     string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	Context        *RequestContext        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_security_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_security_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetCredentialType() string {
	if x != nil {
		return x.CredentialType
	}
	return ""
}

func (x *AuthenticateRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *AuthenticateRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	HttpMethod    string                 `protobuf:"bytes,3,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	HttpPath      string                 `protobuf:"bytes,4,opt,name=http_path,json=httpPath,proto3" json:"http_path,omitempty"`
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_security_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_security_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RequestContext) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *RequestContext) GetHttpPath() string {
	if x != nil {
		return x.HttpPath
	}
	return ""
}

func (x *RequestContext) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RequestContext) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestContext) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Identity      *Identity              `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_security_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_security_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthenticateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthenticateResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectType   string                 `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAtUnix int64                  `protobuf:"varint,6,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_security_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_security_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *Identity) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Identity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Identity) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Identity) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_security_v1_auth_proto protoreflect.FileDescriptor

const file_security_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16security/v1/auth.proto\x12\x13runtime.security.v1\"\x9d\x01\n" +
	"\x13AuthenticateRequest\x12'\n" +
	"\x0fcredential_type\x18\x01 \x01(\tR\x0ecredentialType\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\x12=\n" +
	"\acontext\x18\x03 \x01(\v2#.runtime.security.v1.RequestContextR\acontext\"\xcc\x02\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1f\n" +
	"\vhttp_method\x18\x03 \x01(\tR\n" +
	"httpMethod\x12\x1b\n" +
	"\thttp_path\x18\x04 \x01(\tR\bhttpPath\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12J\n" +
	"\aheaders\x18\a \x03(\v20.runtime.security.v1.RequestContext.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x14AuthenticateResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x129\n" +
	"\bidentity\x18\x03 \x01(\v2\x1d.runtime.security.v1.IdentityR\bidentity\"\xbd\x02\n" +
	"\bIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12!\n" +
	"\fsubject_type\x18\x02 \x01(\tR\vsubjectType\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12M\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2-.runtime.security.v1.Identity.AttributesEntryR\n" +
	"attributes\x12&\n" +
	"\x0fexpires_at_unix\x18\x06 \x01(\x03R\rexpiresAtUnix\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012r\n" +
	"\vAuthService\x12c\n" +
	"\fAuthenticate\x12(.runtime.security.v1.AuthenticateRequest\x1a).runtime.security.v1.AuthenticateResponseBEZCgithub.com/opencode-sig/runtime-sdk/protobuf/security/v1;securityv1b\x06proto3"

var (
	file_security_v1_auth_proto_rawDescOnce sync.Once
	file_security_v1_auth_proto_rawDescData []byte
)

func file_security_v1_auth_proto_rawDescGZIP() []byte {
	file_security_v1_auth_proto_rawDescOnce.Do(func() {
		file_security_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_v1_auth_proto_rawDesc), len(file_security_v1_auth_proto_rawDesc)))
	})
	return file_security_v1_auth_proto_rawDescData
}

var file_security_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_security_v1_auth_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: runtime.security.v1.AuthenticateRequest
	(*RequestContext)(nil),       // 1: runtime.security.v1.RequestContext
	(*AuthenticateResponse)(nil), // 2: runtime.security.v1.AuthenticateResponse
	(*Identity)(nil),             // 3: runtime.security.v1.Identity
	nil,                          // 4: runtime.security.v1.RequestContext.HeadersEntry
	nil,                          // 5: runtime.security.v1.Identity.AttributesEntry
}
var file_security_v1_auth_proto_depIdxs = []int32{
	1, // 0: runtime.security.v1.AuthenticateRequest.context:type_name -> runtime.security.v1.RequestContext
	4, // 1: runtime.security.v1.RequestContext.headers:type_name -> runtime.security.v1.RequestContext.HeadersEntry
	3, // 2: runtime.security.v1.AuthenticateResponse.identity:type_name -> runtime.security.v1.Identity
	5, // 3: runtime.security.v1.Identity.attributes:type_name -> runtime.security.v1.Identity.AttributesEntry
	0, // 4: runtime.security.v1.AuthService.Authenticate:input_type -> runtime.security.v1.AuthenticateRequest
	2, // 5: runtime.security.v1.AuthService.Authenticate:output_type -> runtime.security.v1.AuthenticateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_security_v1_auth_proto_init() }
func file_security_v1_auth_proto_init() {
	if File_security_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_v1_auth_proto_rawDesc), len(file_security_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_v1_auth_proto_goTypes,
		DependencyIndexes: file_security_v1_auth_proto_depIdxs,
		MessageInfos:      file_security_v1_auth_proto_msgTypes,
	}.Build()
	File_security_v1_auth_proto = out.File
	file_security_v1_auth_proto_goTypes = nil
	file_security_v1_auth_proto_depIdxs = nil
}
