// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: examples/go-template-payment/protobuf/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_examples_go_template_payment_protobuf_payment_v1_payment_proto protoreflect.FileDescriptor

const file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	">examples/go-template-payment/protobuf/payment/v1/payment.proto\x12\n" +
	"payment.v1\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"e\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\x88\x01\n" +
	"\x0fPaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\xaa\x01\n" +
	"\x0ePaymentService\x12H\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1b.payment.v1.PaymentResponse\x12N\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a\x1b.payment.v1.PaymentResponseB`Z^github.com/opencode-sig/runtime-sdk/examples/go-template-payment/protobuf/payment/v1;paymentv1b\x06proto3"

var (
	file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescOnce sync.Once
	file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescData []byte
)

func file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDesc), len(file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDesc)))
	})
	return file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDescData
}

var file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_go_template_payment_protobuf_payment_v1_payment_proto_goTypes = []any{
	(*GetPaymentRequest)(nil),    // 0: payment.v1.GetPaymentRequest
	(*CreatePaymentRequest)(nil), // 1: payment.v1.CreatePaymentRequest
	(*PaymentResponse)(nil),      // 2: payment.v1.PaymentResponse
}
var file_examples_go_template_payment_protobuf_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	1, // 1: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	2, // 2: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.PaymentResponse
	2, // 3: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.PaymentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_go_template_payment_protobuf_payment_v1_payment_proto_init() }
func file_examples_go_template_payment_protobuf_payment_v1_payment_proto_init() {
	if File_examples_go_template_payment_protobuf_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDesc), len(file_examples_go_template_payment_protobuf_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_go_template_payment_protobuf_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_examples_go_template_payment_protobuf_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_examples_go_template_payment_protobuf_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_examples_go_template_payment_protobuf_payment_v1_payment_proto = out.File
	file_examples_go_template_payment_protobuf_payment_v1_payment_proto_goTypes = nil
	file_examples_go_template_payment_protobuf_payment_v1_payment_proto_depIdxs = nil
}
